In [7]:

import sys
!{sys.executable} -m pip install biopandas

In [3]:
import pandas
import numpy as np
import sys,argparse
import time
import os
from biopandas.mol2 import PandasMol2
from Bio.PDB import *
from biopandas.pdb import PandasPdb

In [4]:
pmol = PandasMol2().read_mol2('site.mol2')
#contains atoms
pmol.df.head(3)


atom_id atom_name      x       y       z atom_type  subst_id subst_name  \
0        1         C  5.662 -11.097  73.632       C.2         1      HIS16   
1        2         O  6.578 -11.742  73.127       O.2         1      HIS16   
2        3        CA  5.810 -10.555  75.059       C.3         1      HIS16   

   charge  
0     0.0  
1     0.0  
2     0.0

In [5]:
ppdb_df =  PandasPdb().read_pdb('1i9c.pdb')

In [6]:
atom_df = ppdb_df.df['ATOM']
atom_df.head()

record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
0        ATOM            1                 N                  MET           
1        ATOM            2                CA                  MET           
2        ATOM            3                 C                  MET           
3        ATOM            4                 O                  MET           
4        ATOM            5                CB                  MET           

  chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
0        A               1            ...  14.161   -9.448   46.656   
1        A               1            ...  15.242  -10.147   47.340   
2        A               1            ...  15.101  -11.669   47.282   
3        A               1            ...  14.011  -12.216   47.430   
4        A               1            ...  15.291   -9.693   48.797   

   occupancy  b_factor  blank_4 segment_id element_symbol charge  line_idx  
0        1.0     30.61                                  N    NaN       672  
1        1.0     30.21                                  C    NaN       673  
2        1.0     35.55                                  C    NaN       674  
3        1.0     28.46                                  O    NaN       675  
4        1.0     24.49                                  C    NaN       676  

[5 rows x 21 columns]

In [7]:
atom_df.columns

Index(['record_name', 'atom_number', 'blank_1', 'atom_name', 'alt_loc',
       'residue_name', 'blank_2', 'chain_id', 'residue_number', 'insertion',
       'blank_3', 'x_coord', 'y_coord', 'z_coord', 'occupancy', 'b_factor',
       'blank_4', 'segment_id', 'element_symbol', 'charge', 'line_idx'],
      dtype='object')

In [8]:
#read P2rank predictions
p2rank_pred_df = pandas.read_csv('1i9c.pdb_predictions.csv')


In [9]:
p2rank_pred_df.head()

name         rank     score   probability   sas_points   surf_atoms  \
0  pocket1         1    116.07         0.994          397          191   
1  pocket2         2    106.64         0.993          361          183   
2  pocket3         3      9.02         0.317           58           29   
3  pocket4         4      9.00         0.316           63           30   
4  pocket5         5      7.39         0.231           71           35   

      center_x     center_y     center_z  \
0       7.3103      -4.4831      77.3370   
1       5.5729      36.2659      87.8053   
2     -19.2652      21.9690      88.5728   
3      -6.7129      41.8543      96.6379   
4      12.2077      16.1648      83.3353   

                                         residue_ids  \
0   A_117 A_118 A_120 A_121 A_122 A_123 A_126 A_1...   
1   C_117 C_118 C_120 C_121 C_122 C_123 C_126 C_1...   
2   B_356 B_357 B_358 D_257 D_258 D_259 D_364 D_3...   
3   C_21 C_25 D_407 D_408 D_409 D_414 D_416 D_417...   
4   B_301 B_302 B_305 B_328 B_329 B_338 B_339 B_3...   

                                       surf_atom_ids  
0   92 101 103 106 108 110 115 116 117 118 119 12...  
1   4935 4963 4974 4977 4979 4981 4987 4988 4989 ...  
2   3832 3837 3838 3840 3842 3845 3846 7945 7946 ...  
3   5016 5017 5018 5020 5022 5026 5056 5058 9094 ...  
4   1767 3441 3444 3445 3446 3451 3474 3476 3628 ...

In [10]:
p2rank_pred_df.columns

Index(['name     ', '  rank', '   score', ' probability', ' sas_points',
       ' surf_atoms', '   center_x', '   center_y', '   center_z',
       ' residue_ids', ' surf_atom_ids'],
      dtype='object')

In [11]:
#for each pocket get from atom_df the corresponding coordinates
for index, row in p2rank_pred_df.iterrows():
    
    #get pocket atom ids
    ids = row[' surf_atom_ids'].split()
    print(len(ids))

    #get the corresponding coordinates
    pocket_atom_xyz = atom_df[atom_df['atom_number'].isin(ids)]
    print(pocket_atom_xyz)  
    
    #use row[name]for the output file
    out_file = row['name     ']+".pdb"
    
    #save the pdb file with the desired fields
    pocket_atom_xyz[['record_name', 'atom_number', 'blank_1', 'atom_name', 
       'residue_name', 'blank_2', 'chain_id', 'residue_number', 'insertion',
       'blank_3', 'x_coord', 'y_coord', 'z_coord', 'occupancy', 'b_factor',
       'blank_4', 'segment_id', 'element_symbol']].to_csv(out_file,index=False,header=False,sep=' ')
    


191
     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
91          ATOM           92                 O                  SER           
100         ATOM          101               OD1                  ASP           
102         ATOM          103                 N                  CYS           
105         ATOM          106                 O                  CYS           
107         ATOM          108                SG                  CYS           
...          ...          ...     ...       ...     ...          ...     ...   
4789        ATOM         4791                CA                  GLY           
4790        ATOM         4792                 C                  GLY           
4791        ATOM         4793                 O                  GLY           
4797        ATOM         4799                CG                  LYS           
4799        ATOM         4801                CE                  LYS           

     chain_id  residue_number inser

25
     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
3079        ATOM         3081               OD1                  ASN           
3080        ATOM         3082               ND2                  ASN           
3089        ATOM         3091                 N                  ILE           
3093        ATOM         3095                CB                  ILE           
3094        ATOM         3096               CG1                  ILE           
3095        ATOM         3097               CG2                  ILE           
3097        ATOM         3099                 N                  GLN           
3895        ATOM         3897                CA                  GLU           
3897        ATOM         3899                 O                  GLU           
3898        ATOM         3900                CB       A          GLU           
3900        ATOM         3902                CG       A          GLU           
3929        ATOM         3931        

     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
5578        ATOM         5581                 O                  VAL           
5580        ATOM         5583               CG1                  VAL           
6467        ATOM         6471                 O                  ARG           
6476        ATOM         6480                CA                  ALA           
6488        ATOM         6492                CB                  VAL           
6489        ATOM         6493               CG1                  VAL           
6490        ATOM         6494               CG2                  VAL           
6496        ATOM         6500                 N                  LEU           
6501        ATOM         6505                CG                  LEU           
6502        ATOM         6506               CD1                  LEU           
6523        ATOM         6527                 O                  GLU           
6524        ATOM         6528           

     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
4991        ATOM         4994                CB                  ALA           
5009        ATOM         5012               OD1                  ASN           
5017        ATOM         5020                CG       A          LYS           
5023        ATOM         5026                NZ       A          LYS           
5048        ATOM         5051               OD2                  ASP           
5135        ATOM         5138                 O                  ASN           
5137        ATOM         5140                CG                  ASN           
5139        ATOM         5142               ND2                  ASN           
5142        ATOM         5145                 C                  ILE           
5143        ATOM         5146                 O                  ILE           
5148        ATOM         5151                 N                  GLY           
5149        ATOM         5152           

     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
3456        ATOM         3458                CD                  LYS           
3457        ATOM         3459                CE                  LYS           
3458        ATOM         3460                NZ                  LYS           
4795        ATOM         4797                 O                  LYS           
4804        ATOM         4806                 O                  GLY           
6637        ATOM         6641                 O                  GLY           
6639        ATOM         6643                CA                  GLY           
8631        ATOM         8635                CB                  LYS           
8633        ATOM         8637                CD                  LYS           
8634        ATOM         8638                CE                  LYS           
8635        ATOM         8639                NZ                  LYS           
8642        ATOM         8646           

     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
1130        ATOM         1132                CA                  ASP           
1132        ATOM         1134                 O                  ASP           
1133        ATOM         1135                CB                  ASP           
1134        ATOM         1136                CG                  ASP           
1135        ATOM         1137               OD1                  ASP           
1136        ATOM         1138               OD2                  ASP           
1162        ATOM         1164               CD2                  PHE           
1164        ATOM         1166               CE2                  PHE           
1170        ATOM         1172                CB                  HIS           
1171        ATOM         1173                CG                  HIS           
1172        ATOM         1174               ND1                  HIS           
1174        ATOM         1176           

     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
5915        ATOM         5919                 N                  MET           
5919        ATOM         5923                CB                  MET           
5922        ATOM         5926                CE                  MET           
5986        ATOM         5990               CZ2                  TRP           
6059        ATOM         6063               OE1                  GLN           
6088        ATOM         6092               OE1                  GLU           
6121        ATOM         6125               OE1                  GLN           
7163        ATOM         7167               OD2                  ASP           
7178        ATOM         7182                CZ                  ARG           
7424        ATOM         7428                CG                  LYS           
7425        ATOM         7429                CD                  LYS           
7427        ATOM         7431           

9
     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
7968        ATOM         7972               NE2                  GLN           
8803        ATOM         8807               OE2                  GLU           
8822        ATOM         8826               CG1                  VAL           
8853        ATOM         8857               OE1                  GLU           
8854        ATOM         8858               OE2                  GLU           
9253        ATOM         9257                 O                  VAL           
9263        ATOM         9267                CD                  ARG           
9265        ATOM         9269                CZ                  ARG           
9422        ATOM         9426               OD1                  ASN           

     chain_id  residue_number insertion  ... x_coord  y_coord  z_coord  \
7968        D             260            ... -15.784   29.411   87.595   
8803        D             368            ... -20.

16
     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
7667        ATOM         7671                CA                  PRO           
7669        ATOM         7673                 O                  PRO           
7689        ATOM         7693                CA                  GLY           
7690        ATOM         7694                 C                  GLY           
7691        ATOM         7695                 O                  GLY           
7699        ATOM         7703                 N                  LEU           
7700        ATOM         7704                CA                  LEU           
7707        ATOM         7711                 N                  VAL           
7710        ATOM         7714                 O                  VAL           
7711        ATOM         7715                CB                  VAL           
7713        ATOM         7717               CG2                  VAL           
7748        ATOM         7752        

     record_name  atom_number blank_1 atom_name alt_loc residue_name blank_2  \
7667        ATOM         7671                CA                  PRO           
7669        ATOM         7673                 O                  PRO           
7689        ATOM         7693                CA                  GLY           
7690        ATOM         7694                 C                  GLY           
7707        ATOM         7711                 N                  VAL           
7710        ATOM         7714                 O                  VAL           
7711        ATOM         7715                CB                  VAL           
7713        ATOM         7717               CG2                  VAL           
7748        ATOM         7752                OG       A          SER           
7915        ATOM         7919                 C                  GLY           
7916        ATOM         7920                 O                  GLY           
7920        ATOM         7924           

In [28]:


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument('input_toconvert',  
                        nargs='?'
                        )
    parser.add_argument('input_pdb',  
                        nargs='?'
                        )
    parser.add_argument('output',  
                        nargs='?'
                        )
    args = parser.parse_args()
    path_a = args.input_toconvert
    path_b = args.input_pdb
    path_out = args.output
    inter()
   
 
if __name__ == "__main__":
    main(sys.argv[1:])

usage: ipykernel_launcher.py [-h] [input_toconvert] [input_pdb] [output]
ipykernel_launcher.py: error: unrecognized arguments: -f


SystemExit: 2

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3351: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


The overall layout of a Structure object follows the so-called SMCRA (Structure/Model/Chain/Residue/Atom) architecture:

    A structure consists of models
    A model consists of chains
    A chain consists of residues
    A residue consists of atoms


In [14]:
p = PDBParser()
structure = p.get_structure("1i9c", "1i9c.pdb")
#for model in structure:
#    for chain in model:
#        for residue in chain:
#            for atom in residue:
#                print(atom)

#There are also some shortcuts:

# Iterate over all atoms in a structure
for atom in structure.get_atoms():
    print(a.get_name()  # atom name (spaces stripped, e.g. 'CA')
    print(a.get_id()  # id (equals atom name)
    print(a.get_coord()  # atomic coordinates
    print(a.get_vector()  # atomic coordinates as Vector object
    print(a.get_bfactor()  # isotropic B factor
    print(a.get_occupancy()  # occupancy
    print(a.get_altloc()  # alternative location specifier
    print(a.get_sigatm()  # std. dev. of atomic parameters
    print(a.get_siguij()  # std. dev. of anisotropic B factor
    print(a.get_anisou()  # anisotropic B factor
   print( a.get_fullname()  # atom name (with spaces, e.g. '.CA.')

# Iterate over all residues in a model
#for residue in model.get_residues():
#    print(residue)


C:\ProgramData\Anaconda3\lib\site-packages\Bio\PDB\StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 10415.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\Bio\PDB\StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 10506.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\Bio\PDB\StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain C is discontinuous at line 10562.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\Bio\PDB\StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain D is discontinuous at line 10653.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\Bio\PDB\StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 10709.
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\Bio\PDB\StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain B is discontinuous at line 10834.
  warnings.warn(
C:\Program

[14.161 -9.448 46.656]
[ 15.242 -10.147  47.34 ]
[ 15.101 -11.669  47.282]
[ 14.011 -12.216  47.43 ]
[15.291 -9.693 48.797]
[ 16.239 -10.444  49.707]
[ 15.677 -10.385  51.426]
[ 14.583 -11.805  51.482]
[ 16.229 -12.325  47.07 ]
[ 16.416 -13.766  47.101]
[ 15.922 -14.37   48.415]
[ 16.222 -13.856  49.49 ]
[ 17.894 -14.14   46.928]
[ 18.146 -15.141  45.809]
[ 19.525 -14.928  45.207]
[ 20.501 -15.466  45.776]
[ 19.613 -14.214  44.183]
[ 15.165 -15.462  48.389]
[ 14.651 -16.015  49.647]
[ 15.751 -16.679  50.485]
[ 16.601 -17.35   49.895]
[ 13.543 -17.02   49.364]
[ 12.897 -17.67   50.583]
[ 12.358 -19.053  50.213]
[ 10.882 -19.21   50.542]
[ 10.401 -20.552  50.082]
[ 15.681 -16.461  51.784]
[ 16.454 -16.988  52.881]
[ 15.551 -17.294  54.09 ]
[ 14.444 -16.766  54.203]
[ 17.555 -16.033  53.338]
[ 18.529 -15.567  52.276]
[ 19.381 -16.738  51.824]
[ 20.406 -16.258  50.79 ]
[ 21.431 -17.345  50.655]
[ 16.05  -18.146  54.976]
[ 15.341 -18.58   56.171]
[ 15.921 -17.997  57.447]
[ 17.118 -17.952  

[ 15.372 -10.79   76.286]
[12.391 -8.952 75.296]
[11.787 -7.697 75.703]
[11.84  -7.483 77.208]
[11.881 -6.338 77.645]
[10.309 -7.652 75.285]
[ 9.919 -7.403 73.835]
[10.715 -6.246 73.228]
[10.073 -8.633 72.98 ]
[11.81  -8.571 77.979]
[11.456 -8.49  79.39 ]
[12.591 -8.092 80.327]
[12.3   -7.875 81.498]
[10.798 -9.789 79.838]
[ 11.556 -11.052  80.056]
[ 12.774 -11.36   79.485]
[ 10.99  -12.023  80.886]
[ 13.412 -12.561  79.733]
[ 11.625 -13.216  81.14 ]
[ 12.843 -13.487  80.564]
[ 13.474 -14.684  80.805]
[13.808 -7.968 79.823]
[14.962 -7.508 80.526]
[15.9   -8.607 80.978]
[17.058 -8.274 81.203]
[15.416 -9.845 81.125]
[ 16.293 -10.906  81.641]
[ 17.09  -11.571  80.531]
[ 17.806 -12.545  80.772]
[ 15.463 -11.914  82.449]
[ 14.819 -11.285  83.675]
[ 13.989 -12.106  84.61 ]
[ 13.727 -11.646  85.725]
[ 13.511 -13.297  84.251]
[ 17.011 -11.045  79.301]
[ 17.783 -11.647  78.225]
[ 19.287 -11.571  78.437]
[ 20.052 -12.312  77.803]
[ 19.767 -10.715  79.32 ]
[ 21.207 -10.64   79.602]
[ 21.634 -11.9

[29.569 -6.136 74.601]
[30.153 -7.181 74.327]
[30.862 -3.998 74.414]
[31.874 -4.757 75.263]
[33.229 -4.067 75.329]
[34.262 -4.777 74.458]
[35.051 -5.805 75.198]
[28.733 -6.045 75.629]
[28.337 -7.178 76.46 ]
[27.763 -8.31  75.63 ]
[28.109 -9.482 75.767]
[27.329 -6.695 77.488]
[26.651 -7.708 78.38 ]
[26.072 -7.214 79.694]
[26.461 -5.897 80.112]
[25.878 -4.809 80.532]
[24.576 -4.724 80.72 ]
[26.639 -3.745 80.8  ]
[26.835 -7.97  74.726]
[26.209 -9.034 73.941]
[27.04  -9.507 72.762]
[ 26.988 -10.675  72.395]
[24.832 -8.537 73.468]
[23.774 -8.621 74.566]
[23.669 -7.62  75.51 ]
[22.891 -9.69  74.638]
[22.711 -7.678 76.5  ]
[21.929 -9.748 75.626]
[21.826 -8.74  76.554]
[27.8   -8.625 72.139]
[28.743 -9.069 71.099]
[29.827 -9.966 71.689]
[ 30.251 -10.952  71.079]
[29.342 -7.854 70.402]
[28.53  -7.294 69.239]
[29.208 -6.028 68.739]
[28.556 -5.43  67.503]
[29.492 -4.442 66.87 ]
[30.297 -9.666 72.896]
[ 31.259 -10.523  73.567]
[ 30.674 -11.901  73.876]
[ 31.44  -12.86   73.972]
[31.753 -9.866 74.8

[-11.606 -25.114  93.992]
[-10.324 -25.205  94.469]
[ -9.205 -25.469  96.616]
[ -9.116 -25.17   93.803]
[ -7.998 -25.432  95.943]
[ -7.964 -25.286  94.545]
[-14.326 -27.148  99.488]
[-14.518 -27.379 100.922]
[-13.2   -27.209 101.655]
[-12.115 -27.112 101.086]
[-15.093 -28.772 101.183]
[-14.145 -29.705 100.706]
[-16.279 -29.076 100.292]
[-13.319 -27.161 102.972]
[-12.118 -26.934 103.787]
[-11.141 -28.067 103.547]
[ -9.929 -27.865 103.472]
[-12.556 -26.762 105.235]
[-13.213 -25.447 105.576]
[-12.892 -24.396 104.987]
[-14.086 -25.419 106.479]
[-11.667 -29.283 103.38 ]
[-10.83  -30.471 103.257]
[-10.022 -30.555 101.971]
[ -8.835 -30.88  101.932]
[-11.783 -31.683 103.418]
[-12.286 -31.823 104.852]
[-13.44  -30.929 105.245]
[-14.127 -30.282 104.42 ]
[-13.693 -30.859 106.475]
[-10.6   -30.249 100.844]
[-10.174 -30.106  99.482]
[ -9.057 -29.044  99.527]
[ -7.96  -29.29   99.061]
[-11.269 -29.689  98.491]
[-12.498 -30.551  98.433]
[-13.644 -30.252  97.507]
[-14.068 -29.102  97.235]
[-14.202 -31

[-6.891  8.202 94.028]
[-6.198  9.191 94.263]
[-8.137  8.783 91.911]
[-9.434  8.833 91.315]
[-7.313  7.79  91.09 ]
[-6.532  6.969 94.338]
[-5.218  6.683 94.892]
[-4.233  6.187 93.848]
[-4.612  5.427 92.955]
[-5.392  5.7   96.063]
[-5.946  6.492 97.257]
[-5.904  5.525 98.765]
[-6.619  6.657 99.955]
[-2.984  6.611 93.956]
[-1.947  6.326 92.961]
[-1.021  5.22  93.423]
[-0.534  5.198 94.566]
[-1.149  7.595 92.676]
[-0.753  4.277 92.526]
[4.3000e-02 3.1110e+00 9.2869e+01]
[ 1.033  2.864 91.738]
[ 0.537  2.739 90.618]
[-0.817  1.859 93.099]
[-2.2000e-02  6.3600e-01  9.3491e+01]
[-0.847 -0.61  93.761]
[-2.026 -0.673 93.437]
[-0.217 -1.609 94.379]
[ 2.323  2.8   92.015]
[ 3.297  2.42  91.   ]
[ 3.496  0.911 90.889]
[ 2.919  0.137 91.643]
[ 4.596  2.997 91.581]
[ 4.428  2.677 93.042]
[ 2.997  3.111 93.299]
[ 4.363  0.566 89.958]
[ 4.917 -0.768 89.807]
[ 6.383 -0.7   90.229]
[ 6.983  0.354 90.06 ]
[ 4.747 -1.273 88.388]
[ 3.25  -1.414 88.021]
[ 3.165 -1.821 86.56 ]
[ 1.797 -2.147 86.201]
[ 0.936

[ 23.763 -18.037  93.757]
[ 23.168 -18.819  94.928]
[ 23.468 -20.278  94.876]
[ 23.543 -13.36   90.665]
[ 24.122 -12.587  89.588]
[ 23.942 -11.091  89.844]
[ 24.84  -10.323  89.496]
[ 23.518 -12.937  88.225]
[ 23.936 -14.274  87.645]
[ 23.865 -14.366  86.131]
[ 24.039 -13.348  85.427]
[ 23.653 -15.479  85.589]
[ 22.824 -10.726  90.435]
[22.526 -9.345 90.784]
[23.413 -8.844 91.905]
[23.827 -7.685 91.943]
[21.071 -9.262 91.228]
[20.165 -9.586 90.177]
[23.675 -9.74  92.854]
[24.576 -9.372 93.957]
[25.948 -9.046 93.398]
[26.535 -8.041 93.786]
[ 24.641 -10.48   95.009]
[ 25.677 -10.313  96.091]
[25.714 -8.942 96.732]
[24.65  -8.431 97.127]
[26.823 -8.369 96.835]
[26.381 -9.894 92.471]
[27.707 -9.803 91.873]
[27.854 -8.566 90.993]
[28.901 -7.911 90.992]
[ 28.002 -11.066  91.053]
[ 29.462 -11.393  90.85 ]
[ 29.666 -12.894  90.674]
[ 29.507 -13.295  89.215]
[ 30.382 -14.436  88.839]
[26.793 -8.256 90.266]
[26.804 -7.185 89.281]
[26.552 -5.827 89.911]
[26.936 -4.81  89.327]
[25.781 -7.486 88.18

[ -0.145 -13.236 102.285]
[  0.344 -13.546 103.697]
[  0.149 -12.784 104.633]
[ -1.402 -14.024 101.968]
[ -2.117 -13.514 100.756]
[ -2.22  -12.173 100.464]
[ -2.778 -14.169  99.779]
[ -2.912 -12.02   99.336]
[ -3.257 -13.218  98.904]
[  1.041 -14.665 103.867]
[  1.608 -14.925 105.2  ]
[  2.684 -13.9   105.526]
[  3.075 -13.619 106.668]
[  2.125 -16.342 105.191]
[  3.224 -13.293 104.469]
[  4.208 -12.243 104.595]
[  3.593 -10.903 104.866]
[  4.232  -9.856 104.961]
[  2.261 -10.85  105.04 ]
[  1.674  -9.59  105.42 ]
[  1.266  -8.696 104.277]
[  0.879  -7.551 104.502]
[  1.329  -9.218 103.058]
[  0.892  -8.411 101.921]
[ -0.602  -8.651 101.742]
[ -1.005  -9.809 101.566]
[  1.646  -8.735 100.644]
[  3.14   -8.643 100.75 ]
[  3.931  -8.398 101.85 ]
[ 4.035 -8.796 99.653]
[  5.253  -8.397 101.502]
[  5.343  -8.645 100.148]
[ 3.825 -9.063 98.288]
[ 6.467 -8.741 99.322]
[ 4.938 -9.16  97.491]
[ 6.24  -9.005 97.986]
[ -1.389  -7.578 101.832]
[ -2.842  -7.705 101.944]
[ -3.627  -7.461 100.679]
[

[ -7.359 -12.686  92.842]
[ -6.643 -11.623  92.49 ]
[ -7.917 -13.435  91.897]
[-7.464 -8.308 92.984]
[-7.557 -7.483 91.794]
[-7.323 -8.224 90.493]
[-6.173 -8.421 90.065]
[-6.53  -6.339 91.877]
[-6.529 -5.408 90.663]
[-5.384 -4.422 90.644]
[-4.883 -4.022 91.718]
[-4.954 -4.019 89.525]
[-8.407 -8.597 89.837]
[-8.314 -9.104 88.449]
[-7.535 -8.134 87.569]
[-7.746 -6.925 87.704]
[-9.797 -9.173 88.065]
[-10.447  -9.55   89.368]
[-9.79  -8.608 90.353]
[-6.652 -8.628 86.71 ]
[-5.847 -7.798 85.837]
[-6.573 -7.373 84.556]
[-6.642 -8.131 83.592]
[-4.578 -8.557 85.449]
[-3.658 -7.812 84.513]
[-3.255 -6.513 84.74 ]
[-3.183 -8.464 83.384]
[-2.395 -5.878 83.859]
[-2.352 -7.845 82.498]
[-1.945 -6.546 82.734]
[-7.135 -6.176 84.52 ]
[-7.981 -5.665 83.467]
[-7.33  -5.501 82.106]
[-7.893 -5.95  81.103]
[-6.173 -4.844 82.005]
[-5.576 -4.572 80.699]
[-5.146 -5.77  79.879]
[-5.    -5.544 78.669]
[-4.342 -3.715 81.035]
[-4.696 -3.112 82.347]
[-5.427 -4.182 83.086]
[-5.009 -6.971 80.416]
[-4.69  -8.158 79.626]

[-25.015  -6.152  89.263]
[-24.955  -7.683  89.225]
[-25.899  -8.325  89.707]
[-25.406  -5.64   87.873]
[-26.589  -6.312  87.229]
[-26.897  -5.845  85.819]
[-26.022  -5.285  85.13 ]
[-28.039  -6.044  85.367]
[-23.868  -8.198  88.647]
[-23.641  -9.632  88.493]
[-23.391 -10.265  89.856]
[-23.88  -11.336  90.188]
[-22.499  -9.923  87.51 ]
[-23.021 -10.149  86.107]
[-23.296  -9.037  85.308]
[-23.256 -11.406  85.567]
[-23.778  -9.207  84.033]
[-23.735 -11.576  84.282]
[-23.993 -10.46   83.511]
[-24.475 -10.571  82.231]
[-22.609  -9.581  90.701]
[-22.382 -10.154  92.024]
[-23.692 -10.349  92.781]
[-23.93  -11.432  93.329]
[-21.431  -9.257  92.813]
[-19.973  -9.41   92.397]
[-19.153  -8.277  92.993]
[-19.434 -10.761  92.816]
[-24.511  -9.31   92.751]
[-25.786  -9.296  93.444]
[-26.765 -10.278  92.809]
[-27.529 -10.941  93.508]
[-26.37   -7.878  93.481]
[-25.539  -7.029  94.461]
[-26.207  -5.714  94.823]
[-25.357  -4.933  95.818]
[-25.189  -5.634  97.125]
[-26.762 -10.387  91.482]
[-27.732 -11

[14.478  4.404 90.472]
[13.587  4.943 91.486]
[13.229  6.406 91.187]
[12.098  6.811 91.503]
[14.181  4.845 92.879]
[15.474  5.61  93.114]
[15.996  5.334 94.511]
[17.187  6.205 94.851]
[18.344  5.945 93.944]
[14.151  7.15  90.578]
[13.881  8.548 90.245]
[12.843  8.769 89.147]
[12.034  9.697 89.273]
[15.211  9.231 89.863]
[16.143  9.323 91.062]
[17.074  8.158 91.27 ]
[17.078  7.211 90.462]
[17.83   8.121 92.28 ]
[12.801  8.045 88.059]
[11.888  8.002 86.939]
[10.511  7.591 87.466]
[ 9.487  8.164 87.106]
[12.298  7.039 85.839]
[10.56   6.609 88.373]
[ 9.323  6.187 89.03 ]
[ 8.718  7.26  89.926]
[ 7.521  7.588 89.797]
[ 9.534  4.902 89.821]
[ 8.313  4.017 89.879]
[ 7.186  4.478 89.757]
[ 8.555  2.722 90.07 ]
[ 9.491  7.848 90.825]
[ 8.956  8.967 91.621]
[ 8.481 10.101 90.73 ]
[ 7.483 10.787 91.006]
[10.005  9.427 92.624]
[ 9.183 10.342 89.619]
[ 8.718 11.353 88.663]
[ 7.315 11.047 88.137]
[ 6.457 11.95  88.154]
[ 9.728 11.495 87.538]
[ 7.081  9.823 87.71 ]
[ 5.77   9.389 87.235]
[ 4.76   9.

[-14.666 -17.138  70.826]
[-14.663 -16.018  70.292]
[-15.591 -17.476  71.702]
[-16.563 -16.54   72.283]
[-15.846 -15.477  73.102]
[-16.158 -14.291  73.   ]
[-17.612 -17.314  73.102]
[-18.39  -16.489  74.107]
[-18.599 -17.963  72.115]
[-14.837 -15.889  73.88 ]
[-13.904 -14.969  74.527]
[-12.561 -15.114  73.818]
[-12.025 -16.22   73.665]
[-13.833 -15.255  76.023]
[-12.961 -14.421  76.924]
[-13.387 -14.693  78.666]
[-14.634 -13.429  78.899]
[-12.016 -13.997  73.357]
[-10.848 -13.917  72.504]
[-10.072 -12.636  72.811]
[-10.594 -11.545  72.628]
[-11.283 -14.016  71.04 ]
[-10.222 -14.239  69.999]
[ -9.016 -14.191  70.325]
[-10.555 -14.485  68.799]
[ -8.847 -12.766  73.321]
[ -8.083 -11.597  73.775]
[ -7.062 -11.203  72.73 ]
[ -6.264 -12.076  72.369]
[ -7.401 -11.94   75.119]
[ -8.356 -12.349  76.241]
[ -6.484 -10.807  75.569]
[ -9.67  -11.599  76.279]
[-7.046 -9.988 72.187]
[-6.08  -9.627 71.138]
[-4.615 -9.835 71.505]
[-4.145 -9.375 72.545]
[-6.277 -8.111 70.939]
[-7.701 -7.902 71.355]
[-7.

[-9.7280e+00 -3.1000e-02  5.0572e+01]
[-10.598   0.151  56.056]
[-10.13   -0.327  57.358]
[-9.484 -1.699 57.178]
[-9.929 -2.534 56.385]
[-11.249  -0.388  58.405]
[-11.727   1.017  58.76 ]
[-12.436  -1.197  57.918]
[-8.382 -1.958 57.874]
[-7.581 -3.117 57.551]
[-6.611 -3.452 58.657]
[-6.43  -2.703 59.617]
[-6.784 -2.817 56.258]
[-5.812 -1.824 56.56 ]
[-5.954 -4.598 58.511]
[-4.907 -4.941 59.461]
[-3.738 -3.981 59.378]
[-3.053 -3.709 60.354]
[-4.457 -6.387 59.216]
[-3.409 -6.897 60.184]
[-3.663 -6.959 61.544]
[-2.173 -7.33  59.726]
[-2.719 -7.447 62.431]
[-1.223 -7.809 60.606]
[-1.483 -7.871 61.962]
[-3.436 -3.346 58.258]
[-2.454 -2.273 58.259]
[-2.816 -1.158 59.237]
[-1.946 -0.587 59.862]
[-2.296 -1.648 56.873]
[-1.171 -0.63  56.791]
[ 0.169 -1.196 57.193]
[ 0.61  -2.161 56.583]
[ 0.815 -0.631 58.209]
[-4.068 -0.776 59.389]
[-4.53   0.206 60.331]
[-4.284 -0.273 61.77 ]
[-3.895  0.508 62.645]
[-6.019  0.457 60.196]
[-6.452  1.775 59.612]
[-8.26   1.806 59.584]
[-8.556  2.871 58.178]
[-4.

[ 26.839 -10.849  87.609]
[ 13.768   7.172 100.721]
[-16.611   9.361  70.071]
[-28.949 -12.753  81.066]
[ -7.758 -12.164  63.104]
[ -2.947 -17.971  69.906]
[-18.455  15.015  72.14 ]
[ -6.892 -22.231  70.421]
[-12.955  -4.937 102.927]
[ 18.714 -18.792  84.215]
[  4.651 -24.448  86.411]
[12.565 14.049 81.93 ]
[ 15.448 -20.061  78.533]
[ 14.914 -21.855 102.459]
[25.613 -9.111 99.941]
[-17.791  16.885  89.405]
[-14.784 -10.815 106.106]
[ -8.277 -25.077  78.269]
[ 16.125 -23.757  98.169]
[ 18.006 -23.125  92.962]
[-21.024   4.335  88.035]
[-29.883  -8.529  92.309]
[ -3.344 -28.986  82.216]
[-21.537   3.425  57.123]
[-29.14    4.013  78.24 ]
[ -5.076  -0.151 113.072]
[ 14.525 -21.967 100.127]
[ 10.496 -28.33  100.601]
[  3.348  -8.727 114.205]
[-6.633 -0.521 52.997]
[ 8.794 16.401 68.586]
[-18.442   7.358  72.389]
[-21.474   6.136  63.841]
[-25.736   5.843  80.964]
[  7.28  -21.264  80.911]
[ 2.732 -3.798 56.442]
[10.482 12.098 70.122]
[-15.183 -21.597  64.529]
[-13.752 -27.645  82.159]
[  0

[ 8.234 50.739 89.636]
[ 8.241 51.896 89.201]
[ 6.435 50.21  87.962]
[ 5.664 49.188 87.098]
[ 4.405 49.806 86.525]
[ 6.595 48.694 86.01 ]
[ 8.9   50.398 90.725]
[ 9.556 51.417 91.538]
[11.036 51.568 91.228]
[11.807 50.629 91.386]
[ 9.387 51.06  93.022]
[ 8.029 51.168 93.407]
[11.496 52.744 90.798]
[12.941 52.959 90.673]
[13.629 53.031 92.043]
[12.938 53.225 93.031]
[13.05  54.325 90.011]
[11.723 54.984 90.183]
[10.698 53.901 90.375]
[14.941 52.894 92.091]
[15.722 52.965 93.325]
[15.442 54.198 94.162]
[15.329 54.157 95.384]
[17.218 52.947 93.003]
[17.676 51.596 92.479]
[19.184 51.479 92.463]
[19.91  52.366 92.914]
[19.652 50.35  91.927]
[15.348 55.327 93.47 ]
[15.112 56.576 94.197]
[13.786 56.583 94.926]
[13.597 57.38  95.855]
[15.204 57.761 93.222]
[16.584 57.937 92.618]
[16.928 56.958 91.518]
[16.058 56.207 91.007]
[18.131 56.95  91.161]
[12.82  55.729 94.581]
[11.574 55.758 95.35 ]
[11.709 54.934 96.624]
[11.072 55.129 97.647]
[10.379 55.205 94.573]
[ 9.827 56.024 93.443]
[ 8.921 55.

[19.296 33.582 96.501]
[18.9   33.395 94.118]
[18.826 34.099 95.324]
[24.136 29.528 94.853]
[25.238 30.191 95.565]
[25.944 31.255 94.728]
[26.391 32.235 95.317]
[26.226 29.051 95.854]
[25.335 27.844 95.9  ]
[24.35  28.067 94.774]
[26.022 31.071 93.419]
[26.58  32.064 92.508]
[25.74  33.337 92.473]
[26.344 34.423 92.471]
[26.703 31.535 91.077]
[27.735 30.426 90.977]
[28.461 30.197 91.965]
[27.833 29.775 89.921]
[24.421 33.169 92.418]
[23.501 34.297 92.424]
[23.573 35.046 93.749]
[23.721 36.268 93.751]
[22.046 33.875 92.139]
[21.084 35.05  92.296]
[21.961 33.273 90.745]
[23.473 34.328 94.858]
[23.543 34.952 96.164]
[24.761 35.859 96.309]
[24.682 37.004 96.754]
[23.572 33.867 97.241]
[23.167 34.405 98.603]
[23.348 33.342 99.677]
[23.883 32.263 99.332]
[ 22.947  33.62  100.822]
[25.898 35.32  95.893]
[27.181 35.998 95.96 ]
[27.156 37.315 95.201]
[27.534 38.36  95.729]
[28.276 35.069 95.419]
[29.029 34.316 96.495]
[30.269 33.638 95.927]
[30.832 32.566 96.854]
[31.47  31.453 96.083]
[26.67  

[ 16.489  33.729 111.056]
[  5.35   36.037 112.675]
[  2.459  37.007 112.188]
[-6.739 46.572 96.444]
[ 14.789  54.716 111.998]
[21.041 25.726 88.223]
[ 1.358 50.659 97.373]
[ 14.782  31.319 100.613]
[ 4.364 54.813 95.195]
[ 14.179  51.664 115.209]
[ 20.063  35.014 103.897]
[17.271 54.884 89.568]
[17.859 28.981 99.274]
[ 17.535  32.88  105.543]
[ 26.352  41.512 102.061]
[  7.689  39.431 117.586]
[ 22.946  46.471 106.456]
[ 28.55   50.586 101.588]
[ 19.902  61.281 105.957]
[19.276 57.358 88.551]
[ 22.074  38.402 112.373]
[16.23  27.913 93.269]
[11.895 58.549 91.783]
[ 10.455  54.264 112.07 ]
[  3.352  31.028 102.677]
[29.165 27.105 89.515]
[ 23.274  38.578 106.732]
[ 0.754 48.213 96.741]
[  8.643  27.434 106.075]
[26.85  41.424 89.475]
[-6.215 63.529 71.799]
[-7.403 63.053 71.089]
[-8.493 62.73  72.098]
[-8.191 62.342 73.234]
[-7.05  61.835 70.248]
[-8.103 61.293 69.311]
[-7.522 59.797 68.463]
[-5.789 60.208 68.233]
[-9.743 62.896 71.676]
[-10.841  62.483  72.558]
[-11.143  61.006  72.29

[ 0.962 34.057 64.646]
[-1.414 33.735 64.671]
[ 1.094 33.454 65.884]
[-1.288 33.12  65.909]
[-4.5000e-02  3.2980e+01  6.6499e+01]
[-2.806 34.926 60.684]
[-4.263 34.972 60.523]
[-4.762 33.859 59.625]
[-5.814 33.25  59.809]
[-4.687 36.314 59.93 ]
[-3.985 33.598 58.573]
[-4.395 32.587 57.605]
[-4.233 31.2   58.197]
[-5.071 30.325 57.968]
[-3.592 32.762 56.299]
[-3.967 34.062 55.6  ]
[-3.045 34.475 54.476]
[-2.264 33.621 54.01 ]
[-3.097 35.651 54.026]
[-3.176 30.955 58.965]
[-3.034 29.68  59.647]
[-4.086 29.441 60.728]
[-4.495 28.286 60.925]
[-1.614 29.52  60.245]
[-1.379 28.04  60.581]
[5.2000e-02 2.7795e+01 6.1034e+01]
[ 0.268 26.371 61.496]
[ 1.725 26.04  61.449]
[-4.559 30.472 61.427]
[-5.683 30.314 62.355]
[-6.94  29.813 61.655]
[-7.677 28.974 62.218]
[-5.999 31.617 63.116]
[-5.01  31.963 64.243]
[-5.165 33.387 64.719]
[-5.162 31.    65.422]
[-7.2   30.35  60.468]
[-8.358 29.948 59.675]
[-8.299 28.457 59.347]
[-9.287 27.734 59.5  ]
[-8.495 30.764 58.379]
[-9.549 30.143 57.475]
[-8.853

[20.564 50.498 74.111]
[21.616 50.476 73.005]
[21.349 49.423 71.942]
[20.371 49.56  71.164]
[22.134 48.45  71.88 ]
[21.251 49.263 76.878]
[22.14  48.839 77.947]
[22.083 47.341 78.168]
[23.079 46.661 78.379]
[21.761 49.544 79.265]
[22.787 49.122 80.316]
[23.948 49.487 80.166]
[22.424 48.348 81.322]
[20.869 46.76  78.119]
[20.803 45.34  78.429]
[21.324 44.476 77.311]
[21.773 43.356 77.528]
[21.252 45.026 76.094]
[21.791 44.299 74.94 ]
[23.297 44.198 75.165]
[23.872 43.129 75.048]
[21.397 44.98  73.631]
[19.943 44.721 73.21 ]
[22.327 44.592 72.491]
[19.301 45.861 72.456]
[23.892 45.331 75.527]
[25.327 45.404 75.785]
[25.789 44.474 76.895]
[26.814 43.8   76.799]
[25.689 46.858 76.134]
[25.75  47.759 74.908]
[27.178 47.89  74.397]
[27.498 46.876 73.307]
[28.915 46.41  73.339]
[25.043 44.431 77.993]
[25.379 43.591 79.128]
[25.233 42.129 78.752]
[26.035 41.292 79.166]
[24.462 43.9   80.322]
[24.728 45.231 81.   ]
[24.275 45.258 82.452]
[24.093 44.171 83.041]
[24.107 46.363 83.021]
[24.182 41.

[-1.358 37.778 66.585]
[-0.324 40.545 66.7  ]
[-1.0000e-02  4.1428e+01  6.7807e+01]
[-0.991 41.106 68.934]
[-2.202 41.118 68.699]
[-5.8000e-02  4.2920e+01  6.7477e+01]
[ 0.472 43.772 68.607]
[ 1.296 43.343 69.419]
[-4.0000e-03  4.5009e+01  6.8667e+01]
[-0.44  40.754 70.077]
[-1.276 40.442 71.24 ]
[-1.532 41.699 72.045]
[-0.698 42.614 72.006]
[-0.556 39.405 72.108]
[-1.37  38.951 73.298]
[-0.627 38.048 74.255]
[ 0.561 37.718 74.03 ]
[-1.249 37.672 75.277]
[-2.648 41.76  72.775]
[-2.898 42.865 73.671]
[-4.204 43.589 73.452]
[-5.007 43.242 72.577]
[-4.402 44.61  74.268]
[-5.564 45.483 74.249]
[-5.442 46.522 75.345]
[-4.552 46.411 76.198]
[-6.33  47.499 75.295]
[-6.24  48.679 76.127]
[-6.592 48.459 77.587]
[-6.24  49.297 78.416]
[-7.267 47.375 77.917]
[-7.497 46.944 79.288]
[-6.456 45.907 79.694]
[-5.81  45.979 80.739]
[-8.906 46.343 79.439]
[-10.019  47.284  78.955]
[-9.17  45.9   80.862]
[-11.375  46.635  78.731]
[-6.285 44.887 78.844]
[-5.506 43.726 79.257]
[-4.016 44.004 79.219]
[-3.25

[-8.13  42.896 75.861]
[-7.787 44.96  76.565]
[-12.354  42.872  71.835]
[-12.707  42.478  70.462]
[-13.602  43.482  69.778]
[-13.432  43.805  68.6  ]
[-13.411  41.123  70.457]
[-14.607  43.998  70.515]
[-15.454  45.006  69.919]
[-14.708  46.288  69.584]
[-14.921  46.897  68.526]
[-16.646  45.332  70.835]
[-17.72  44.26  70.91]
[-18.404  44.328  72.278]
[-18.698  44.429  69.765]
[-13.839  46.759  70.466]
[-13.134  47.998  70.18 ]
[-12.132  47.831  69.029]
[-11.841  48.77   68.273]
[-12.401  48.509  71.422]
[-13.261  48.867  72.642]
[-12.355  49.087  73.842]
[-14.151  50.073  72.407]
[-11.567  46.638  68.89 ]
[-10.695  46.343  67.752]
[-11.471  46.335  66.44 ]
[-11.099  46.897  65.411]
[-9.991 45.012 67.959]
[-12.606  45.654  66.449]
[-13.405  45.555  65.23 ]
[-13.824  46.929  64.725]
[-13.89   47.156  63.518]
[-14.64   44.688  65.467]
[-14.139  47.846  65.659]
[-14.497  49.196  65.207]
[-13.387  49.891  64.426]
[-13.69   50.679  63.513]
[-14.932  50.032  66.408]
[-15.269  51.469  66.061

[ 4.267 24.966 86.376]
[ 2.191 26.473 85.309]
[ 3.629 24.56  85.214]
[ 2.576 25.296 84.702]
[ 4.331 24.762 90.742]
[ 5.199 23.944 91.594]
[ 6.62  23.99  91.043]
[ 6.762 24.013 89.813]
[ 4.655 22.524 91.431]
[ 3.992 22.556 90.081]
[ 3.379 23.938 90.012]
[ 7.61  23.979 91.915]
[ 9.006 23.957 91.495]
[ 9.448 22.596 90.964]
[10.294 22.495 90.08 ]
[ 9.877 24.34  92.689]
[10.25  25.812 92.739]
[11.376 26.141 93.698]
[11.258 27.082 94.496]
[12.486 25.403 93.619]
[ 8.861 21.52  91.469]
[ 9.197 20.188 90.968]
[ 8.801 19.997 89.52 ]
[ 7.629 20.162 89.155]
[ 8.504 19.134 91.852]
[ 8.902 17.719 91.468]
[ 8.291 17.135 90.554]
[ 9.825 17.179 92.087]
[ 9.774 19.64  88.679]
[ 9.501 19.574 87.247]
[ 8.466 18.526 86.88 ]
[ 7.74  18.706 85.904]
[10.813 19.377 86.472]
[11.754 20.565 86.699]
[12.999 20.442 85.824]
[13.005 19.554 84.951]
[13.921 21.248 86.056]
[ 8.341 17.438 87.632]
[ 7.373 16.412 87.286]
[ 5.962 16.909 87.59 ]
[ 5.041 16.718 86.792]
[ 7.682 15.111 88.033]
[ 9.04  14.734 87.798]
[ 5.79  17.

[-24.925  19.146  80.699]
[-24.807  20.348  80.485]
[-23.062  17.531  80.957]
[-22.318  18.653  81.437]
[-25.801  18.682  81.594]
[-26.535  19.678  82.373]
[-25.575  20.543  83.167]
[-25.734  21.762  83.239]
[-27.565  19.063  83.331]
[-28.198  20.152  84.208]
[-29.199  20.975  83.413]
[-28.634  22.191  82.724]
[-29.134  23.494  83.219]
[-24.588  19.877  83.753]
[-23.565  20.614  84.498]
[-22.955  21.728  83.661]
[-22.846  22.894  84.081]
[-22.511  19.611  84.964]
[-22.95   18.658  86.046]
[-23.833  17.493  85.682]
[-24.337  17.314  84.555]
[-24.064  16.67   86.61 ]
[-22.537  21.417  82.447]
[-21.94   22.394  81.539]
[-22.946  23.482  81.167]
[-22.623  24.68   81.189]
[-21.401  21.751  80.261]
[-20.702  22.683  79.266]
[-19.521  23.415  79.912]
[-20.235  21.94   78.022]
[-24.155  23.058  80.81 ]
[-25.214  23.987  80.419]
[-25.455  25.056  81.483]
[-25.599  26.256  81.215]
[-26.492  23.187  80.144]
[-27.61   23.944  79.442]
[-28.933  23.197  79.553]
[-28.898  21.955  79.69 ]
[-29.999  23

[-10.234  49.291  90.84 ]
[-10.763  49.494  92.196]
[-10.155  48.616  93.275]
[-9.951 48.983 94.441]
[-12.258  49.271  92.155]
[-9.832 47.384 92.927]
[-9.265 46.41  93.821]
[-10.25   46.018  94.914]
[-9.789 45.628 95.991]
[-11.553  46.141  94.653]
[-12.565  45.84   95.636]
[-13.084  44.41   95.543]
[-13.216  43.738  96.568]
[-13.783  46.778  95.515]
[-13.473  48.232  95.837]
[-14.644  49.106  95.405]
[-14.483  50.552  95.847]
[-15.8    51.261  95.912]
[-13.373  43.973  94.326]
[-13.834  42.611  94.097]
[-12.752  41.621  94.537]
[-11.566  41.859  94.275]
[-14.207  42.383  92.634]
[-14.829  41.031  92.335]
[-13.645  39.739  91.891]
[-13.405  40.051  90.162]
[-13.193  40.556  95.201]
[-12.359  39.482  95.715]
[-12.868  38.133  95.216]
[-14.04   37.789  95.451]
[-12.315  39.513  97.247]
[-11.186  38.781  97.946]
[-11.62   38.508  99.698]
[-11.15   40.111 100.365]
[-12.007  37.399  94.524]
[-12.342  36.05   94.069]
[-11.875  35.002  95.06 ]
[-10.919  35.2    95.82 ]
[-11.478  35.874  92.809

[-7.843 30.679 99.626]
[-10.418  30.797 101.396]
[-11.031  29.737 102.275]
[-12.779  29.531 101.844]
[-13.232  28.427 103.19 ]
[ -8.417  32.796 100.186]
[-7.888 33.381 98.949]
[-6.384 33.212 98.868]
[-5.764 32.817 97.891]
[-8.241 34.878 98.88 ]
[-7.658 35.534 97.63 ]
[-9.75  35.059 98.905]
[-5.733 33.542 99.988]
[ -4.293  33.392 100.086]
[-3.929 31.93  99.925]
[-3.014 31.583 99.211]
[ -3.855  33.946 101.459]
[ -3.934  35.465 101.57 ]
[ -2.484  33.407 101.818]
[ -3.965  35.922 103.023]
[ -4.712  31.042 100.573]
[ -4.446  29.607 100.387]
[-4.564 29.22  98.919]
[-3.771 28.436 98.386]
[ -5.353  28.731 101.247]
[ -5.187  28.888 102.737]
[ -4.181  29.526 103.103]
[ -6.01   28.386 103.55 ]
[-5.553 29.776 98.221]
[-5.737 29.427 96.822]
[-4.603 29.979 95.97 ]
[-4.245 29.366 94.966]
[-7.082 29.902 96.292]
[-8.267 29.12  96.814]
[-8.063 28.013 97.35 ]
[-9.405 29.628 96.701]
[-4.05  31.126 96.351]
[-2.963 31.743 95.596]
[-1.732 30.834 95.639]
[-0.985 30.727 94.668]
[-2.681 33.139 96.143]
[-3.768 3

[-25.337  44.993  92.014]
[-1.297 34.487 51.933]
[20.337 29.694 64.56 ]
[-1.754 29.348 56.543]
[-13.68   16.508  66.551]
[-19.493  52.429  67.758]
[-21.263  52.608  87.963]
[17.485 48.074 62.786]
[ 7.774 55.669 51.038]
[-24.68   27.868  74.21 ]
[-10.777  44.594  55.409]
[ 5.345 25.893 57.975]
[-25.49   37.409  75.798]
[-28.049  44.404  67.154]
[-10.146  20.096 103.947]
[-28.125  41.583  82.535]
[10.89  15.485 85.802]
[ 9.612 33.219 52.65 ]
[18.018 53.151 66.971]
[ 9.956 39.913 50.571]
[23.36  31.741 77.384]
[-16.554  37.603 103.22 ]
[-17.791  37.08   64.036]
[-15.644  15.165  69.413]
[-24.043  23.587  92.857]
[-9.746 22.71  68.386]
[-1.374 58.764 73.738]
[15.914 19.155 74.158]
[24.851 37.667 68.62 ]
[19.922 29.259 78.618]
[-24.355  51.41   71.135]
[-1.085 61.724 70.087]
[ 7.184 52.483 83.801]
[-1.696 58.59  86.087]
[-9.802 42.225 54.896]
[-14.973  14.261  75.462]
[24.55  41.657 69.52 ]
[ 5.018 60.937 70.606]
[-18.827  26.85   71.423]
[-18.439  22.037 108.597]
[-18.018  53.421  62.134]
