In [4]:
# import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [12]:
import pandas as pd

In [16]:
with tf.Session() as sess:
    new_saver = tf.train.import_meta_graph('our_data/model/model.ckpt.meta')
    new_saver.restore(sess, tf.train.latest_checkpoint('our_data/model'))
    print(sess.run('w1:0'))

INFO:tensorflow:Restoring parameters from our_data/model/model.ckpt


ValueError: Fetch argument 'w1:0' cannot be interpreted as a Tensor. ("The name 'w1:0' refers to a Tensor which does not exist. The operation, 'w1', does not exist in the graph.")

In [1]:
import numpy as geek
c = geek.load('Protein-Structure-DL-master/data/pairwise2d/1a4z_4_0.npz')

In [8]:
import numpy as np
x = np.load('Protein-Structure-DL-master/data/pairwise2d/1a4z_4_0.npz', mmap_mode='r')
for k in x.files:
     print((k))

arr_0


In [18]:
pd.DataFrame(x["arr_0"][0])

0  1  2  3   4  5  6  7  8
0   4  2  2  0   0  0  0  0  0
1   0  0  0  0   0  0  0  0  0
2   0  0  0  0   0  0  0  0  0
3   0  0  0  0   0  0  0  0  0
4   0  0  0  0   0  0  0  0  0
5   0  0  1  1   7  3  0  0  0
6   0  0  1  0   5  1  0  0  0
7   0  0  4  7   5  1  0  0  0
8   0  0  0  0   0  0  0  0  0
9   1  4  7  7  10  1  0  0  0
10  0  0  0  0   0  0  0  0  0
11  1  2  3  2   0  0  0  0  0
12  0  2  4  3   2  1  0  0  0
13  0  0  0  1   1  1  0  0  0
14  0  0  0  0   0  0  0  0  0
15  0  2  2  2   4  2  0  0  0
16  0  0  0  0   0  0  0  0  0
17  0  0  2  4   2  0  0  0  0
18  0  1  6  2   0  0  0  0  0
19  0  0  0  0   0  0  0  0  0
20  0  0  0  0   2  1  0  0  0
21  0  0  0  0   0  0  0  0  0
22  0  1  2  0   0  0  0  0  0

In [22]:
print(x["arr_0"][2])

[[0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 2 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 2 4 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [11]:
with tf.Session() as sess:
        saver = tf.train.import_meta_graph('our_data/model/model.ckpt.meta')
        saver.restore(sess, 'our_data/model/model.ckpt')
        print(tf.global_variables())

INFO:tensorflow:Restoring parameters from our_data/model/model.ckpt
[<tf.Variable 'conv2d/kernel:0' shape=(5, 5, 9, 128) dtype=float32_ref>, <tf.Variable 'conv2d/bias:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization/gamma:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization/beta:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization/moving_mean:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization/moving_variance:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'conv2d_1/kernel:0' shape=(5, 5, 128, 128) dtype=float32_ref>, <tf.Variable 'conv2d_1/bias:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization_1/gamma:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization_1/beta:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization_1/moving_mean:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'batch_normalization_1/moving_variance:0' shape=(128,) dtype=float32_ref>, <tf.Variabl

In [25]:
import csv
import os

path = os.walk("convertions30")
total_pocks = []
with open('ta_dika_mas_pocks.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    for root, directories, files in path:
        for file in files:
            print(file)
            writer.writerow([file[:-4]+",0,0"])

6fd3_pocket1.pdb
2ycf_pocket1.pdb
5lqf_pocket1.pdb
5ew8_pocket1.pdb
5yf9_pocket1.pdb
3e7o_pocket1.pdb
4z55_pocket2.pdb
1u59_pocket1.pdb
4ckj_pocket1.pdb
4bkj_pocket1.pdb
3sxs_pocket1.pdb
4bgq_pocket1.pdb
4z55_pocket1.pdb
3aln_pocket2.pdb
1u59_pocket2.pdb
4asz_pocket1.pdb
2wel_pocket2.pdb
3v5w_pocket1.pdb
3iec_pocket2.pdb
4hcu_pocket1.pdb
3dls_pocket1.pdb
4hvs_pocket1.pdb
2xrw_pocket1.pdb
2dq7_pocket1.pdb
5te0_pocket2.pdb
1byg_pocket1.pdb
4asz_pocket2.pdb
3kmu_pocket2.pdb
2eva_pocket1.pdb
3kul_pocket1.pdb
5uyj_pocket1.pdb
1s9i_pocket1.pdb
2ac3_pocket1.pdb
2fst_pocket1.pdb
2r4b_pocket1.pdb
3omv_pocket1.pdb
5mja_pocket1.pdb
6cz4_pocket2.pdb
5k00_pocket1.pdb
6fnk_pocket1.pdb
2vz6_pocket1.pdb
4lg4_pocket1.pdb
4qtc_pocket1.pdb
4l6q_pocket1.pdb
4pf4_pocket1.pdb
4af3_pocket1.pdb
2xir_pocket1.pdb
3dtc_pocket1.pdb
2buj_pocket1.pdb
3fe3_pocket1.pdb
4y85_pocket1.pdb
4asz_pocket3.pdb
2vz6_pocket2.pdb
2j0i_pocket1.pdb
2xik_pocket1.pdb
5j5t_pocket1.pdb
3my0_pocket1.pdb
3fhr_pocket1.pdb
5o1v_pocket1.p